---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: nginx-mtls
  namespace: perf-https-linkerd
spec:
  client:
    meshTLS:
      serviceAccounts:
        - name: nginx-ingress
          namespace: ingress-nginx
  server:
    name: nginx
